services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=platzi_play_db'
      - 'POSTGRES_PASSWORD=App$2025'
      - 'POSTGRES_USER=platzi'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: